name       : libxau
version    : 1.0.8
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXau-1.0.8.tar.bz2 : fdd477320aeb5cdd67272838722d6b7d544887dfe7de46e1e7cc0c27c2bea4f2
license    :
    - MIT
summary    : X Authorization Protocol library
component  : xorg.library
builddeps  :
    - pkgconfig(xproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    The libXau package contains a library implementing the X11 Authorization Protocol. This is useful for restricting client access to the display.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
