name       : libxau
version    : 1.0.10
release    : 19
source     :
    - https://gitlab.freedesktop.org/xorg/lib/libxau/-/archive/libXau-1.0.10/libxau-libXau-1.0.10.tar.bz2 : 8562ceb1de70d7ec7eb0df58a8f3ab8ab3c9ad7f5518950f9bb2d94591ecbfec
license    : MIT
component  : xorg.library
summary    : X Authorization Protocol library
description: |
    The libXau package contains a library implementing the X11 Authorization Protocol. This is useful for restricting client access to the display.
builddeps  :
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
