name       : libxau
version    : 1.0.9
release    : 16
source     :
    - https://gitlab.freedesktop.org/xorg/lib/libxau/-/archive/libXau-1.0.9/libxau-libXau-1.0.9.tar.bz2 : 2fda6ab0d68a7cc2da51e48d1b42e77b57eaf33aed51b6768a9072d3acee06f5
license    : MIT
component  : xorg.library
summary    : X Authorization Protocol library
description: |
    The libXau package contains a library implementing the X11 Authorization Protocol. This is useful for restricting client access to the display.
builddeps  :
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
